docs/miden/index.md, docs/zkEVM/get-started/zkevm-gas-station.md, mkdocs.yml
Fixed one miden/index image link + added zkevm-gas-station.md
=> update and adding gas station doc

docs/_site_essentials/stylesheets/polygon-docs.webflow.css
This change makes the front page look nice on mobile devices.
=> Fix landing page responsiveness

docs/_site_essentials/stylesheets/extra.css, docs/tools/index.md
- Isolate CSS
- Clean up HTML
- Remove unused jQuery library being loaded
=> Clean up Tools landing page code

docs/index.md, mkdocs.yml
- Added a new link with text to replace Tutorials.
- Added the google analytics code.
=> Fix front page and add analytics code

docs/pos/operate-node/validator/kb/how-to.md
=> Update PoS - fixed links 

docs/tools/matic-js/get-started.md, docs/tools/matic-js/installation.md, docs/tools/matic-js/pos/client.md, docs/tools/matic-js/zkevm/initialize.md, mkdocs.yml
This PR is work done on https://polygon.atlassian.net/browse/TKDW-21
I think it was already there, just difficult to see. 
The whole of this tools section needs a major rewrite.
As a quick fix, I have done a little restructure of the menu and adding some clarifying terms. Let's see if it's sufficient for now.
=> Clarifying the matic.js zkEVM bridge documentation

mkdocs.yml
Added a menu item **Third-party tutorials** and included the tutorial as requested.
=> Add Alchemy tutorial to tools section

docs/index.md
Adding Edge details to front page of the docs.
=> Add edge note to front page

docs/cdk/index.md, docs/index.md, docs/miden/index.md, docs/pos/index.md, docs/tools/index.md, docs/zkEVM/index.md, mkdocs.yml
This PR unifies all section front pages to have the same look and feel/styling.
It also fixes some html problems with elements not getting hidden where they should be, etc.
=> Tidying up the html

overrides/main.html, overrides/partials/integrations/analytics/custom.html
Adding GTM codes to tag manager account.
=> Add gtm details

overrides/main.html
It's not working immediately and to test a fix I have to raise a PR every time.
Here's another. 
We're getting closer.
=> Git contributors: trying once again

.github/workflows/dev_deployment.yml, .github/workflows/prod_deployment.yml
=> Bumping python up in prod and dev

docs/_site_essentials/stylesheets/polygon-docs.webflow.css, mkdocs.yml
This PR removes the white box border on both menus and also fixes a format issue that got in from the recent author plugin update.
=> Remove white box and format issues

docs/zkEVM/architecture/protocol/state-management.md
Updating state-management.md in response to a query on Slack here https://0xpolygon.slack.com/archives/C061ADK8534/p1704495242278529
=> Update state-management.md - zkEVM

docs/zkEVM/architecture/protocol/transaction-life-cycle/batch-sequencing.md
Fixes as per request: https://0xpolygon.slack.com/archives/C061ADK8534/p1704661190515219
=> Update zkEVM doc: batch-sequencing.md

docs/zkEVM/architecture/protocol/malfunction-resistance/sequencer-resistance.md
Update zkEVM doc: sequencer-resistance.md
i.e., Fixes as per request: https://0xpolygon.slack.com/archives/C061ADK8534/p1704942655395349
=> Update zkEVM doc: sequencer-resistance.md

docs/zkEVM/architecture/zknode/index.md
Update zkEVM - add endpoints ... in response to the request here https://0xpolygon.slack.com/archives/C061ADK8534/p1705070519246269
=> update zkEVM - add endpoints

docs/miden/vm/architecture/introduction.md, docs/miden/vm/architecture/stack/field-ops.md, docs/miden/vm/tools/debugger.md, docs/pos/architecture/index.md, docs/pos/concepts/transactions/index.md, docs/zkEVM/how-to/index.md, docs/zkEVM/spec/index.md
Made some text corrections found on the documentation.
=> Text corrections

docs/cdk/get-started/quickstart-validium.md
Updating the validium quickstart to include info about extra views and nonce resetting.
=> A few small changes to validium quickstart

docs/pos/concepts/transactions/meta-transactions.md, docs/pos/reference/contracts/genesis-contracts.md
- Update Biconomy CTAs
- Copy edits
- Modify to make code blocks work
- Update contract address CTAs, official Amoy explorer not available, using oklink explorer links
=> PoS - Broken links, copy edits

docs/zkEVM/get-started/deploy-zkevm/deploy-zknode.md
Update zkEVM - fix expandable text as per https://github.com/0xPolygon/polygon-docs/pull/172 by @toanalien
=> Update zkEVM - fix expandable text

docs/learn/agglayer.md
=> Update Learn - agglayer.md

docs/learn/agglayer.md
Update agglayer with latest doc written by Brendan
=> Update source doc for agglayer .md

docs/learn/agglayer.md
Update agglayer.md - fixing minor typos
=> Update agglayer.md - fixing minor typos

docs/pos/reference/rpc-endpoints.md
Adding Amazon Managed Blockchain to the RPC list
=> Adding a new RPC service to the list.

docs/cdk/get-started/connect-testnet.md
Add chain id and how to auto set up a wallet as well as link out to MM docs.
=> Update stavanger testnet info

docs/tools/smart-contracts/crossmint.md
I made a few minor edits for us to keep track of analytics through utm_source and campaigns. 
This helps us understand the users that are being redirected to our docs, product, etc through the Polygon docs. Eventually, we will use the inferences drawn from the analytics to provide more catered content for the Polygon ecosystem and community
@kmurphypolygon can you please merge this? Thank you!
And it would also be helpful if this can get added to https://docs.polygon.technology/pos/how-to/smart-contracts/ since the old docs (before migration) had this tutorial under that category as well. 
Thank you so much, looking forward to your response!
=> Updating crossmint.md to include internal analytics

docs/learn/agglayer.md
Update Learn - AggLayer doc: Fixing rendering within tables
=> Update Learn - AggLayer doc

docs/cdk/get-started/deploy-rollup/install-dependencies.md
Removing an instruction regarding environment variables which broke a users PATH and probably mine too when I think about it.
=> Remove dodgy path setting

docs/zkEVM/architecture/protocol/security-council.md
=> zkevm security council doc review, update security-council.md

docs/zkEVM/get-started/setup-nodes/production-node.md
Update production-node.md ... including "cardona" as per request https://0xpolygon.slack.com/archives/C061ADK8534/p1706780001660679
=> Update zkEVM - production-node.md

mkdocs.yml
Unmuting Type-1 prover docs ... in mkdocs.yml
=> Update mkdocs.yml - Unmuting Type-1 prover docs

docs/cdk/index.md
Quick PR to fix a broken link on CDK frontpage.
=> Fix broken link on CDK

docs/zkEVM/get-started/setup-nodes/production-node.md
Update production-node.md - latest Cardona v0.5.7
=> Update production-node.md - latest Cardona

docs/pos/how-to/bridging/ethereum-polygon/index.md
- Remove /img/home/
- Remove irrelevant info regarding zkEVM bridge
=> Update bridging index page

docs/learn/deep-dive-arch.md, docs/learn/index.md, mkdocs.yml
Removed the Polygon 2.0 architecture deep dive post in favour of the reorg PoS post.
=> Remove/replace Learn post

docs/zkEVM/architecture/user-fees.md
Update user-fees.md - minor typos
=> Update user-fees.md - minor typos

docs/cdk/version-matrix.md, mkdocs.yml
- Adding important info about component versions per CDK release.
- Also adding related zkEVM info at the same time.
Note: I did it in html as we had some merged cells and markdown couldn't deal with it. I used an online html table generator for this.
=> CKD compatibility version matrix

docs/zkEVM/architecture/protocol/etrog-upgrade.md
Update zkEVM - correcting "type-2" to "almost type 2" ... in etrog-upgrade.md
=> Update zkEVM - almost type 2

docs/zkEVM/architecture/user-fees.md
Update user-fees.md - removing the "$\texttt{ }$" styling on sidebar titles
=> Update user-fees.md - fix sidebar titles

docs/cdk/get-started/deploy-validium/contracts/deploy-contracts.md, docs/cdk/get-started/deploy-validium/contracts/prerequisites.md, docs/cdk/get-started/deploy-validium/contracts/set-up.md, docs/cdk/get-started/deploy-validium/intro.md, docs/cdk/get-started/deploy-validium/node/configure-deployment.md, docs/cdk/get-started/deploy-validium/node/run-node-services.md, docs/cdk/get-started/deploy-validium/node/set-up.md
Corrections to flow and user issues.
=> Updating the validium deployment guide with input from SME review

docs/cdk/how-to/quick-test-stack.md, mkdocs.yml
Do describing quick ways to test a running CDK stack.
Requesting review from SME @praetoriansentry
=> CDK: How to quickly test a transaction

docs/cdk/get-started/connect-testnet.md, docs/cdk/get-started/deploy-validium/contracts/deploy-contracts.md, docs/cdk/get-started/deploy-validium/contracts/prerequisites.md, docs/cdk/get-started/deploy-validium/contracts/set-up.md, docs/cdk/get-started/deploy-validium/intro.md, docs/cdk/get-started/deploy-validium/node/configure-deployment.md, docs/cdk/get-started/deploy-validium/node/prerequisites.md, docs/cdk/get-started/deploy-validium/node/run-node-services.md, docs/cdk/get-started/deploy-validium/node/set-up.md, docs/cdk/get-started/deploy-validium/node/test-transaction.md, docs/cdk/get-started/quickstart-rollup.md, docs/cdk/get-started/quickstart-validium.md
Adding the feedback function to the CDK Get started section docs for user input.
=> Adding the feedback button to CDK docs

docs/zkEVM/architecture/zkprover/main-state-machine/index.md, docs/zkEVM/architecture/zkprover/main-state-machine/processor.md
update zkEVM docs - typos and MS style review ... including changes suggested in https://github.com/0xPolygon/polygon-docs/pull/262
=> update zkEVM docs - typos and MS style review

docs/cdk/index.md, docs/pos/concepts/tokens/pol.md
Incredibly low-priority typo fixes. 
(´・ω・｀)
=> Typo fix: 1 repeated word, 1 accidental capital

docs/zkEVM/architecture/user-fees.md
Update zkEVM docs - Edit "User fees" doc ... https://polygon.atlassian.net/browse/DOCS-79
=> Update zkEVM docs - Edit "User fees" doc

mkdocs.yml
I broke the menu in the last PR this is the fix.
=> fixing menu

.gitignore, docs/cdk/how-to/integrate-agglayer.md, docs/cdk/resources/third-party-guides.md, mkdocs.yml
- The doc content comes from here: https://github.com/0xPolygon/agglayer
- The local installation runs, I'm not sure how to test it in production - todo? 
- It's not clear how I can test the AggLayer functionality fully - todo?
- This PR fixes something that broke in an earlier PR.
=> CDK: AggLayer how-to

docs/zkEVM/get-started/state-sync-snapshots.md
Update zkEVM snapshots ... as per issue https://polygon.atlassian.net/browse/DOCS-84
=> Update zkEVM snapshots

docs/zkEVM/architecture/user-fees.md, docs/zkEVM/get-started/historical-data.md
update zkEVM user fees -  fixing equation rendering 
+ 
update "Historical data" doc with new links to 'instructions' ... as per issue https://polygon.atlassian.net/browse/DOCS-88
=> update zkEVM user fees - equation rendering

docs/cdk/how-to/agglayer/configure.md, docs/cdk/how-to/agglayer/local-install.md, docs/cdk/how-to/agglayer/openrpc.md, mkdocs.yml
- For now, in the how tos.
- Later on this may be better in an API section.
=> CDK: Adding the OpenAPI playground to the How Tos

docs/pos/how-to/full-node/full-node-ansible.md
Reverts 0xPolygon/polygon-docs#299
=> Revert "Email obfuscation fix test"

docs/zkEVM/architecture/user-fees.md, docs/zkEVM/get-started/deploy-zkevm/install-dependencies.md
Update zkEVM - Install dependencies doc ... as per the issue https://polygon.atlassian.net/browse/DOCS-102?atlOrigin=eyJpIjoiNzhiZWY4NzQ4ZjJkNDA4ZThjY2VlYjI1ODY1MTg5MTIiLCJwIjoiaiJ9
=> Update zkEVM - Install dependencies doc

docs/pos/reference/rpc-endpoints.md
In this PR, we add Amoy Network config in RPC endpoints in docs.
=> Add Amoy network in rpc-endpoints.md

docs/tools/data/envio.md, mkdocs.yml
We are a supported data indexing framework for Polygon PoS, zkEVM, and CDK and on the Polygon Solutions Provider Network.
=> adds envio to polygon docs as supported data indexer

docs/tools/data/moralis.md, mkdocs.yml
Added Moralis as an API provider to the list of data tools in the Polygon documentation
=> Added Moralis to Data tools page

docs/tools/data/subquery.md, mkdocs.yml
Hello Polygon team,
We are submitting this contribution with the intention of incorporating SubQuery into your project documentation. As you can observe, we have already prepared the initial project. Kindly inform us if any adjustments are necessary on our part.
=> featured SubQuery

docs/zkEVM/api/json-rpc.md, docs/zkEVM/api/zkevm.openrpc.json, mkdocs.yml
Pushing the json to live, first.
=> zkEVM RPC endpoints

docs/cdk/version-matrix.md
Update versions:
- CDK-Etrog Release- BETA TESTING validium node
- CDK Elderberry 2 Release bridge
=> CDK: update version compatibility matrix

docs/zkEVM/get-started/setup-nodes/production-node.md
Update zkEVM - remove Goerli in setup production node ... as per issue https://polygon.atlassian.net/browse/DOCS-128
=> Update zkEVM -remove Goerli in setup production node

docs/tools/gas/polygon-gas-station.md
- Add zkEVM cardona and mainnet gas oracle URLs
=> Dev tools: Update gas station

docs/zkEVM/get-started/deploy-zkevm/create-wallets.md
Update method calls for ethers:
_signingKey() to signingKey
_mnemonic() to mnemonic
=> Update create-wallets.md wallets.js bugs.

docs/zkEVM/api/json-rpc.md
There was an extra URL I removed.
=> zkEVM: quick fix of the rpc issue

docs/cdk/version-matrix.md
Version updates https://polygon.atlassian.net/browse/DOCS-139
=> CDK: update matrix

docs/pos/get-started/becoming-a-validator.md, docs/pos/how-to/snapshots.md, docs/pos/how-to/validator/prerequisites.md, docs/pos/reference/rewards.md, docs/tools/wallets/walletkit.md, mkdocs.yml
Breaking links due to turning off warnings.
=> Fix broken local links

mkdocs.yml
Looking for a language review on this one. 
Technical correctness done.
=> CDK: kurtosis quick start

mkdocs.yml
- first test is to comment out some instant features from the docs platform
=> Platform: testing fix for unrendered equations - first test

docs/zkEVM/architecture/proving-system/exec-selector-columns.md
update zkEVM - equation fix in Proving system docs
=> update zkEVM - equation fix

docs/cdk/architecture/type-1-prover/intro-t1-prover.md, docs/cdk/architecture/type-1-prover/t1-architecture.md, docs/cdk/architecture/type-1-prover/t1-cpu-component.md, docs/cdk/architecture/type-1-prover/t1-design-challenge.md, docs/cdk/architecture/type-1-prover/testing-and-proving-costs.md, docs/cdk/index.md, docs/cdk/overview.md, docs/cdk/version-matrix.md, docs/learn/index.md, docs/learn/plonky.md, docs/learn/polygon-protocols.md, docs/learn/welcome.md, mkdocs.yml
Plus a few other style alignment changes.
=> Learn: Plonky page

docs/zkEVM/architecture/effective-gas/implement-egp-strat.md, docs/zkEVM/architecture/effective-gas/index.md, docs/zkEVM/architecture/effective-gas/user-tx-flow/rpc-flow-egp.md, docs/zkEVM/architecture/effective-gas/user-tx-flow/sequencer-flow-egp.md, docs/zkEVM/architecture/effective-gas/zkevm-egp-strat.md, docs/zkEVM/spec/user-fees/breakeven-technique.md
Update zkEVM - Edit user fees: Adding examples ... related to https://polygon.atlassian.net/browse/DOCS-78
=> Update zkEVM - Edit user fees

docs/zkEVM/get-started/historical-data.md
Update zkEVM - Historical data doc ... as per issue: https://polygon.atlassian.net/browse/DOCS-199
=> Update zkEVM - Historical data doc 

docs/cdk/version-matrix.md
Update contracts release on fork id 9.
=> CDK: matrix update

docs/tools/chain-indexer-framework/overview.md, docs/tools/matic-js/installation.md
These are the changes that involves the changes to 2 pages.
1. ChainIndexer Framework
2. Matic.Js installation page
=> Updates Dev tools pages updates 

docs/zkEVM/architecture/index.md, docs/zkEVM/architecture/protocol/transaction-life-cycle/submit-transaction.md, docs/zkEVM/overview.md
Update zkEVM - Tokenomics doc ... as per issue https://polygon.atlassian.net/browse/DOCS-115
=> Update zkEVM - Tokenomics doc

docs/zkEVM/get-started/state-sync-snapshots.md
Quick tidy of the state sync doc.
=> Update the state sync doc

docs/index.md
I thought I did this last week but it was included in a PR I then closed.
=> Urgent fix of front page 404s

docs/zkEVM/get-started/setup-nodes/production-node.md
https://polygon.atlassian.net/browse/DOCS-158
Also, some style guide improvements.
=> Updating the production node install Cardona requirements

docs/zkEVM/get-started/quick-start.md
Update zkEVM - fix Cardona link ... issue https://polygon.atlassian.net/browse/DOCS-220
=> Update zkEVM - fix Cardona link

docs/tools/index.md, mkdocs.yml
=> add oklink api url - katharine dealing with this one

docs/zkEVM/how-to/check-tx-status.md, mkdocs.yml
zkEVM update: Adding tx status check doc ... as per ticket https://polygon.atlassian.net/browse/DOCS-266
=> zkEVM update: Adding tx status check doc

mkdocs.yml
Reverts 0xPolygon/polygon-docs#502
=> Revert "remove config"

docs/index.md, mkdocs.yml
Urgent fix of frontpage 404s and Learn section rename.
=> Fix frontpage 404s and new section

docs/pos/get-started/becoming-a-validator.md, docs/pos/how-to/troubleshoot/technical-faqs.md, docs/pos/reference/contracts/stakingmanager.md
- Update active validator limit
- Language fixes
- Remove/update outdated info
=> PoS: active validator limit

docs/tools/gas/matic-faucet.md, mkdocs.yml
Changes:
- Add GetBlock faucet link
- Language fixes
- Nav bar restructure
=> Add getblock faucet link

overrides/partials/header.html
This PR includes the meta tag so we can access google search data.
=> URGENT FIX: update header to access search

docs/tools/gas/polygon-gas-station.md
Updated gas station url for testnet
=> doc: updated test net gasstation url in documentation

docs/zkEVM/architecture/protocol/index.md
This PR fixes a typo. Free for anyone to self-assign and review.
=> fix(zkevm): fix typo

docs/zkEVM/architecture/zkprover/storage-state-machine/construct-key-path.md, docs/zkEVM/architecture/zkprover/storage-state-machine/index.md, docs/zkEVM/concepts/sparse-merkle-trees/detailed-smt.md, docs/zkEVM/concepts/sparse-merkle-trees/sparse-merkle-tree.md, mkdocs.yml
zkEVM - Quality Assurance 1 - fix small errors ... as per issue https://polygon.atlassian.net/browse/DOCS-305
=> zkEVM - Quality Assurance 1 - fix small errors

docs/tools/oracles/chronicle.md, mkdocs.yml
Add Chronicle to Oracles list as well as an example on how to read data
=> Add Chronicle to Oracles list

mkdocs.yml
Updating polyfill to cloudflare service.
=> Updating polyfill url

mkdocs.yml
This PR fixes the imported menu from kurtosis and adds back the how-to docs.
=> CDK: menu fix

docs/zkEVM/get-started/state-sync-snapshots.md
zkEVM update - Adding snapshots admonition ... resolving the issue https://polygon.atlassian.net/browse/DOCS-277
=> zkEVM update - Adding snapshots admonition

docs/tools/data/sqd.md, mkdocs.yml
Hi - please add SQD to your docs. We have been supporting Polygon for some time: https://docs.subsquid.io/subsquid-network/reference/evm-networks/.
=> tools-update

overrides/404.html
This PR adds custom html so that 404's can be tracked properly on Google Analytics.
=> Platform: Add custom 404 for GA

.github/assets/nginx.conf
Adding security header as per request from security team.
=> Platform: Add CSP to nginx config

docs/pos/how-to/snapshots.md
- Update for community snapshot as primary method
- Remove old Polygon snapshot platform
=> PoS: update snapshots.md

docs/index.md
- Front page link needed pointing to the docs instead of blog.
- Moved AggLayer up in the list.
=> AggLayer: Update AggLayer link

mkdocs.yml
This PR adds a redirection system that allows us to do our own redirections internally.
From here, we can disconnect from devops doing them and manage the 404s ourselves.
=> Platform: Adds internal redirects system

docs/zkEVM/architecture/data-streamer/client-server-messages.md, docs/zkEVM/architecture/data-streamer/how-rollbacks-work.md, docs/zkEVM/architecture/data-streamer/server-source-library.md, docs/zkEVM/architecture/data-streamer/stream-file.md, mkdocs.yml
zkEVM - QA edits - datastreamer ... as per issue https://polygon.atlassian.net/browse/DOCS-334
=> zkEVM - QA edits - datastreamer

docs/cdk/concepts/admin-upgradeability.md, docs/cdk/concepts/architecture.md, docs/cdk/concepts/blocks.md, docs/cdk/concepts/bridging.md, docs/cdk/concepts/gas-fees.md, docs/cdk/concepts/layer2s.md, docs/cdk/concepts/rollup-vs-validium.md, docs/cdk/concepts/transaction-finality.md, docs/cdk/concepts/transaction-lifecycle.md, docs/cdk/concepts/zk-vs-optimistic.md, docs/cdk/index.md, docs/cdk/resources/third-party-guides.md, docs/index.md, docs/pos/how-to/validator/validator-packages.md, mkdocs.yml
- Updates after review session with team.
- This one reviews the concepts section which reads well, although there is one question about whether some of these docs should be in the architecture section rather than the concept section as they are less generalized.
- Apart from that, these changes are mostly links, and some styling.
- Found the descriptions of rollup, validium, zkEVM etc, compelling.
=> CDK: Review concepts

docs/cdk/agglayer/overview.md
AggLayer - Insert table of connected chains ... as per issue https://polygon.atlassian.net/browse/DOCS-341
=> AggLayer - Insert table of connected chains

docs/zkEVM/architecture/index.md, docs/zkEVM/index.md, docs/zkEVM/overview.md
zkEVM - edit main-overview doc ... as per issue https://polygon.atlassian.net/browse/DOCS-342
=> zkEVM - edit main-overview doc

docs/cdk/agglayer/overview.md
AggLayer - Add a new connected chain to list ... as per issue https://polygon.atlassian.net/browse/DOCS-343
=> AggLayer - Add a new connected chain to list

docs/tools/oracles/ora.md, mkdocs.yml
Add ORA to Oracles list and a quickstart guide on how developers can use ORA Onchain AI Oracle on Polygon.
=> Add ORA to Oracles list

docs/index.md
Home page - fix 404 on AggLayer link in Home page ... as per issue https://polygon.atlassian.net/browse/DOCS-348
=> Home page - fix 404 on AggLayer link in Home page

docs/cdk/version-matrix.md
Update compability matrix - version-matrix.md ... as per issue https://polygon.atlassian.net/browse/DOCS-349
=> Update compability matrix - version-matrix.md

docs/innovation-design/agglayer/overview.md
AggLayer - add 2 connected chains to list ... as per issue https://polygon.atlassian.net/browse/DOCS-355
=> AggLayer - add 2 connected chains to list

docs/cdk/version-matrix.md
CDK - version compatibility matrix ... as per issue https://polygon.atlassian.net/browse/DOCS-358
=> CDK - version compatibility matrix

docs/tools/storage/filecoinhelpers.md, docs/zkEVM/how-to/using-foundry.md
Update outdated descriptions for NFT.Storage flagship product and classic.
=> NFT.storage update

docs/cdk/getting-started/cdk-erigon/index.md, mkdocs.yml
Move CDK Erigon docs to zkEVM ... as per discussion with @gsilva5
=> Moving CDK Erigon docs to zkEVM

docs/tools/matic-js/pos/erc1155/withdraw-exit-many.md, docs/tools/matic-js/pos/erc1155/withdraw-start.md, sitemap.xml
- Updating the sitemap to include changes since last upload.
=> Platform: Update sitemap

docs/cdk/resources/cdk-repo-reference.md
- Added some clarifying comments to an older document.
=> Learn: Small update to old doc to force prod update

docs/tools/gas/matic-faucet.md
- Add StakePool faucet link to the faucet table
=> Dev tools: add stakepool faucet

docs/pos/concepts/tokens/matic.md
- Update links to fix 404 error
=> PoS: update matic.md

docs/cdk/getting-started/local-deployment.md
Removed as part of this PR: https://github.com/0xPolygon/kurtosis-cdk/pull/258
=> Remove tool_check as it is no longer in the repo

docs/cdk/version-matrix.md
- Remove unnecessary rows.
- Keep the content in comments in case we need it back.
=> CDK: Update the release matrix doc

docs/agglayer/overview.md
This PR adds `haust` chain details.
=> AggLayer: Add new chain details

docs/miden/index.md
Small update to trigger a new import of Miden.
=> Miden: New import

.github/assets/dev-taskdef.json, .github/workflows/build_and_deploy.yml, .github/workflows/pr-deployment.yml, Dockerfile.review, build_branches.py, nginx.conf
Deployment fix for dev deployment through hosted/<branch> PRs
=> Deployment fix for dev deployment through hosted/<branch> PRs

.github/workflows/pr-deployment.yml
Fix for trigger to non default branch PR.
=> Spec 170 dev deployment update for review

.github/workflows/build_and_deploy.yml
Check and stop building if no files were changed
=> Check and stop building if no files were changed

docs/cdk/getting-started/local-deployment.md
Updates to match the kurtosis cdk repo changes.
=> CDK: Updating local deployment guide

.github/workflows/build_and_deploy.yml, .github/workflows/hosted-dev-deployment.yml, build_branches.py
Deployment fixes to be added for consistence to dev
=> Consistent deployment update

.github/workflows/build_and_deploy.yml, .github/workflows/hosted-dev-deployment.yml
some description.
Modify description.
=> Update if statement when the build should trigger

.github/workflows/build_and_deploy.yml, .github/workflows/hosted-dev-deployment.yml
Hosted url: [docs-dev.polygon.technology/749](https://docs-dev.polygon.technology/749)
=> Fix for hosted deployment branch

docs/cdk/how-to/connect-testnet.md
Added information about Stavanger testnet issues.
=> CDK: Add warning re Stavanger testnet

docs/cdk/getting-started/cdk-erigon/deploy-cdk-erigon.md
CDK erigon - update RAM required from 32GB to 64GB ... as per issue https://polygon.atlassian.net/browse/DOCS-400
=> CDK erigon - update RAM required

docs/agglayer/overview.md
https://polygon.atlassian.net/browse/DOCS-411
=> AggLayer: Remove deprecated chain

overrides/partials/comments.html
We're been spammed a couple of time through giscus.
This PR attempts to block that happening.
=> Security: Strengthen git discussions

docs/robots.txt
Add disallows to remove erroneous attempts at indexing.
=> Platform: Add disallows

docs/cdk/architecture/cdk-validium.md, docs/cdk/architecture/cdk-zkevm.md, docs/cdk/concepts/rollup-vs-validium.md, docs/zkEVM/architecture/effective-gas/user-tx-flow/sequencer-flow-egp.md, docs/zkEVM/architecture/effective-gas/zkevm-egp-strat.md
Pool manager is described in different ways across the docs. This PR consolidates the terms as much as possible.
=> CDK: Update pool manager wording

docs/cdk/getting-started/local-deployment.md
Some updates after latest releases.
=> CDK: Update deployment guide

docs/cdk/how-to/integrate-da.md, mkdocs.yml
CDK: update integrate DA ... as per issue https://polygon.atlassian.net/browse/DOCS-409
=> CDK: update integrate DA

mkdocs.yml
Sidebar: Rename "Unified Bridge - STB"  --> "Staking the Bridge (STB)" as per Gabe's review of docs.
=> Sidebar: Rename Unified Bridge - STB

docs/cdk/spec/validium-vs-rollup.md
CDK: rollup v validium - fix links
=> CDK: rollup v validium - fix links

docs/robots.txt, sitemap.xml
This PR adds a new updated sitemap and removes the disallows from robots.
=> Platform: Update sitemap and robots txt

mkdocs.yml
CDK Erigon: To appear under CDK section ... just navigational change.
=> CDK Erigon: To appear under CDK section 

docs/cdk/getting-started/cli-tool.md
=> Update cli-tool.md for PP

docs/agglayer/overview.md
Added the Witness chain to the agglayer list.
=> Added new chain to Agglayer list

docs/cdk/how-to/migrate/forkid-9-12.md
Changed text in a callout section
=> Text-Update forkid-9-12.md

docs/tools/data/thegraph.md, mkdocs.yml
This PR contains changes for: 
- `mkdocs.yml`: Added navigation item conforming to alphabetical order
- `tools/thegraph.md`: Contains a full walk through on how to setup a subgraph
Please let me know if anything needs to be updated to get published.
=> Added section for the graph: quick start full guide

docs/agglayer/architecture/pessimistic-proof.md, docs/agglayer/architecture/unified-bridge.md, docs/agglayer/crosschain-interop/crosschain-interop.md, docs/agglayer/overview.md, docs/cdk/concepts/pessimistic-proofs.md
I made some stylistic changes to the unified bridge docs and fixed the file paths from the overview.md file.
=> agglayer overview.md file paths

docs/agglayer/overview.md, docs/index.md, docs/innovation-design/index.md
fixing broken file paths and restyling AggLayer to Agglayer site-wide* (except across the Learn sections)
=> agglayer overview, main index, and innovation index

docs/agglayer/architecture/pessimistic-proof.md, docs/agglayer/overview.md
additional styling and file path corrections
=> overview.md and pessimisticproof.md

.github/workflows/build_and_deploy_gcp.yml, .github/workflows/deploy_gcp.yml
GCP Deployment for docker image updated.
=> GCP Deployment for docker image updated.

docs/pos/reference/network-upgrade-process.md
In the 2nd step of upgrade process, the # was not correctly align which was causing issue.
=> Little change in the 2nd step

docs/pos/reference/telemetry-setup-guide.md, mkdocs.yml, sitemap.xml
=> Added new doc to setup telemetry

docs/tools/gas/matic-faucet.md
Removed Polygon Faucet Details as the Faucet is Decommissioned
=> Removed Polygon Faucet Details as the Faucet is Decommissioned 

.github/workflows/build_and_deploy_gcp.yml, .github/workflows/deploy_gcp.yml
Update workflow to update docker image tag required for hosting
=> Update workflow to update docker image tag required for hosting

.github/workflows/build_and_deploy_gcp.yml, .gitignore
=> Fix for CI build

.github/assets/polygon-docs-dev-taskdef.json, .github/assets/polygon-docs-staging-taskdef.json, .github/assets/polygon-docs-taskdef.json
Hosted url: [docs-dev.polygon.technology/2647](https://docs-dev.polygon.technology/2647)
=> Updated DD eu integration

docs/pos/architecture/heimdall_v2/authentication.md, docs/pos/architecture/heimdall_v2/balance-transfers.md, docs/pos/architecture/heimdall_v2/governance.md, docs/pos/architecture/heimdall_v2/introduction.md
Update auth, balance transfer and governance with heimdalld instead of simd for the cosmos modules
=> Replace simd with heimdalld

docs/pos/architecture/heimdall_v2/clerk.md, docs/pos/architecture/heimdall_v2/heimdallv2_swagger.yaml, docs/pos/architecture/heimdall_v2/introduction.md
Update some docs for heimdall-v2 based on latest development
=> v2 docs update
