mkdocs.yml
Right now, "Developer tools" is taking up double the size of the second-largest section and triple the average size of all other sections in the navigation bar.
- Home: 3 squares
- CDK: 2 squares
- zkEVM: 4 squares
- PoS: 2 squares
- Miden: 3 squares
- Developer tools: 8 squares
- Learn: 3 squares
It's not appropriate design to have a miscellaneous section take up triple the average navigation size of the main product sections.
Please accept this commit to revert the change.
=> Revert "Developer tools" heading

docs/index.md
There was an order misalignment of divs on the BUILD box which is now fixed.
=> Fixing Edge front page styling

mkdocs.yml
I changed the analytics tracking method from plain Google Analytics to GTM-based tracking.
This is done so that the partial override file we have added in the repo gets loaded on the `docs.polygon.technology` website.
=> [Updated] Analytics Tracking Method

mkdocs.yml, overrides/main.html, requirements.txt
Devops says they could not fix the issue with losing data between environments, so I'm trying again with a different plugin. Let's see if this works. 
Locally, it's pretty good:
=> Adding git contributors

.github/workflows/staging_deployment.yml, requirements.txt
There is a dependency mismatch in environments.
This PR goes along with a python bump in the actions. 
Hopefully it will fix the plugin issues.
=> Downgrading material version

mkdocs.yml
The correct branding and name for the product is "thirdweb" all in small cases
=> Update mkdocs.yml to change "ThirdWeb" to "thirdweb"

mkdocs.yml
Typo on the menu of the zkEVM documentation:
- `Trasaction life cycle` -> `Transaction life cycle`
=> Update zkevm menu docs

docs/pos/reference/mapped-tokens.md
Solves the formatting issue of the mainnet mapped tokens table.
By the way, I highly suggest using [prettier](https://prettier.io/) in a CI job to check if changes made to the docs respect the correct formatting! This would prevent issues like this one :)
=> fix: mainnet mapped tokens table

docs/zkEVM/concepts/sparse-merkle-trees/simple-smt.md
Case 1 shows that Ka = 11010110 and Kb = 11010101.
I think there is a mistake and Kb should be 11010111.
=> Fixing typo in Kb binary value for Case 1

docs/zkEVM/get-started/setup-nodes/production-node.md
-  The recommended version of the Cardano network has been updated from 0.5.5 to 0.5.12, as indicated on [Github](https://github.com/0xPolygonHermez). 
- Let people know updated location.
=> CHANGE cardona recommend version

mkdocs.yml, requirements.txt
Removing the author plugin for two reasons:
- It conflicts with the import plugin currently.
- It makes working on local extremely slow.
=> Remove author plugin

mkdocs.yml
Small addition to mkdocs which imports the Miden client docs.
I have tested this and it works so just need an OK.
=> Include the Miden client docs as an import

docs/zkEVM/architecture/protocol/security-council.md
There was some misinformation (eg. amount of Polygon signers) that is now corrected
=> Fix zkEVM Secity Council Info

docs/cdk/get-started/quickstart-validium.md
we completed the updates for [zkValidium-quickstart](https://github.com/Snapchain/zkValidium-quickstart) with the 0.6.4-cdk.2.
Now all the updates are under the branch `v0.0.3`, and we will merge it to `main` once this PR is merged and [polygon-docs](https://github.com/0xPolygon/polygon-docs) is published.
=> update quickstart-validium for 0.6.4-cdk.2

docs/learn/index.md
The Security link was pointing to `../security/overview`, should be `./security/overview`
=> Error on Security Link

docs/pos/reference/rpc-endpoints.md
Moralis recently launched our RPC node service again. This MR is updating the link to go straight to our nodes page.
=> Updated link to Moralis nodes

docs/tools/dApp-development/third-party-tutorials.md, docs/zkEVM/how-to/index.md, mkdocs.yml
- Consolidate third-party tutorials in dev tools space
- In-house smart contract dev tutorials classified into PoS and zkEVM
- Add zkEVM 'how-to' tutorials to the zkEVM category
- Modify mkdocs.yml to delete 'how-to' section from zkEVM space
- Files continue to live in the zkEVM directory (to avoid 404s)
=> Dev tools, zkEVM: migrating how-tos

docs/cdk/glossary/index.md, docs/innovation-design/index.md, docs/innovation-design/polygon-protocols.md, docs/innovation-design/welcome.md
This PR covers:
- Remove references to Polygon 2.0 to avoid confusion.
- Change "Interop layer" -> "Agglayer"
- Add EIP links
- Miden testnet update
- Other minor fixes
=> I&D, CDK: remove polygon 2.0

docs/pos/how-to/snapshots.md
- Slightly modifying the structure to provide better visibility for Amoy community snapshots
- Changing `amoy` network option for snapshot CLI back to `mumbai` since Amoy is not, and will not be supported
=> PoS: snapshot CLI network option

docs/cdk/version-matrix.md, mkdocs.yml
`version-matrix.md` doc removed in error.
This PR adds back the most up to date doc.
=> CDK: Add the compatibility matrix back in

mkdocs.yml
DipDup is a Python framework for building smart contract indexers. It helps developers focus on business logic instead of writing a boilerplate to store and serve data.
https://dipdup.io/docs
=> Added link to DipDup docs

docs/pos/reference/port-management.md
The heimdall uses port 26656 for peer connection and synchronization.
=> POS: Heimdall Port review

mkdocs.yml
- This PR includes the Miden compiler documentation.
- Currently on branch `next`.
=> Miden: include miden compiler docs

.github/workflows/dev_deployment.yml
I would like the build to auto-run every 30 minutes to accommodate DevRel Learn writing flow, and to allow us to keep pushing content no matter timezone / availability. We will leave prod pushes as manual.
=> Automate dev builds

.github/workflows/dev_deployment.yml
This prevents image conflicts. When a github commit is put onto AWS, it uses the commit as hash of the image. If nothing has changed, then it will fail because the ECR is immutable and cannot have images overwriting. So we need to change the image tag to be different on every run, in this case, we append the run number. Should be fine.
=> Add run number to image tag

.github/workflows/dev_deployment.yml
- The scheduling is in the way of the other triggers so the environment doesn't build on a push or PR.
- Just commenting it out while we don't need it but can add back when necessary.
=> Platform: Removing dev scheduling (for now at least)

docs/pos/concepts/tokens/pol.md
=> PoS: Update POL reference doc

.github/assets/polygon-docs-dev-taskdef.json, .github/assets/polygon-docs-staging-taskdef.json, .github/assets/polygon-docs-taskdef.json
Hosted url: [docs-dev.polygon.technology/2456](https://docs-dev.polygon.technology/2456)
Fix for taskdef template after datadog integration enabled
=> Fix for taskdef template after datadog integration enabled

docs/agglayer/overview.md
I removed the following deprecated chain from the list
- Wirex devnet
- OKX devnet
I also updated Haust mainnet chain id to 938
=> Removed deprecated chain from the list

docs/zkEVM/architecture/protocol/incentive-mechanism.md
I remove all mentions of MATIC token and MATIC and replaced with POL in the  incentive-mechanism.md page of the zKEVM documentation
=> removed all MATIC mention to POL in incentive-mechanism.md page

docs/cdk/getting-started/local-deployment.md
Update doc and specify how to PP chain
=> Update local-deployment.md with PP config

docs/cdk/releases/pp-intro-components.md, mkdocs.yml
DRAFT:CDK - Add pp intro + components descriptions doc
=> DRAFT:CDK - Add pp intro doc

docs/tools/wallets/appkit.md, docs/tools/wallets/reown.md, mkdocs.yml
WalletConnect Inc. is now known as Reown. This PR adds a dedicated doc page for Reown and also updates the Web3Modal reference, which was rebranded to Reown AppKit.
Closes issue #2518
=> Docs Update: Adding Reown as one of the available wallet tools on Polygon

Dockerfile
Add `bash` to the aline docker image so that `docker compose up` will work with the multirepo plugin.
=> Update docker file to have bash so mkdocks-multibranch works
